version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports: ['27017:27017']
    volumes:
      - mongo-data:/data/db
  server:
    build: ./server
    environment:
      - MONGO_URI=mongodb://mongo:27017/realestate
      - JWT_SECRET=devsecret
    ports: ['5000:5000']
    depends_on: ['mongo']
  client:
    build: ./client
    ports: ['5173:3000']
volumes:
  mongo-data:
